<?php

namespace ProjxIO\Logic;

use PHPUnit_Framework_TestCase;

class StreamBuilderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var StreamBuilder
     */
    private $stream;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stream = new StreamBuilder();
    }

    public function test()
    {
        $this->assertTrue(call_user_func($this->stream->equalTo(5)->equalTo(true), 5));
    }

    public function testA()
    {
        $this->assertTrue(call_user_func($this->stream->equalTo(6)->equalTo(false), 5));
    }

    public function testMap()
    {
        $expect = [false, true, false];
        $stream = $this->stream
            ->map($this->stream->equalTo(4));
        $actual = call_user_func($stream, collect([3, 4, 5])->items());
        $this->assertEquals($expect, $actual);
    }
}
